version: 5.1.0
variant: default
logo: /img/logo.svg
head:
    favicon: /img/favicon.svg
    manifest:
        name:
        short_name:
        start_url:
        theme_color:
        background_color:
        display: standalone
        icons:
            -
                src: ''
                sizes: ''
                type:
    open_graph:
        title:
        type: blog
        url:
        image:
        site_name:
        author:
        description:
        twitter_card:
        twitter_id:
        twitter_site:
        google_plus:
        fb_admins:
        fb_app_id:
    structured_data:
        title:
        description:
        url:
        author:
        publisher:
        publisher_logo:
        image:
    meta:
        - ''
    rss:
navbar:
    menu:
        Home: /
        Archives: /archives
        Categories: /categories
        Tags: /tags
    links:
        Download on GitHub:
            icon: fab fa-github
            url: https://github.com/InverseDa
footer:
    links:
        Creative Commons:
            icon: fab fa-creative-commons
            url: https://creativecommons.org/
        Attribution 4.0 International:
            icon: fab fa-creative-commons-by
            url: https://creativecommons.org/licenses/by/4.0/
        Download on GitHub:
            icon: fab fa-github
            url: https://github.com/InverseDa
article:
    highlight:
        theme: atom-one-dark
        clipboard: true
        fold: unfolded
    readtime: true
    update_time: true
    licenses:
        Creative Commons:
            icon: fab fa-creative-commons
            url: https://creativecommons.org/
        Attribution:
            icon: fab fa-creative-commons-by
            url: https://creativecommons.org/licenses/by/4.0/
        Noncommercial:
            icon: fab fa-creative-commons-nc
            url: https://creativecommons.org/licenses/by-nc/4.0/
search:
    type: insight
    index_pages: true
comment:
    type: utterances
    repo: InverseDa/inverseda_blog_comments
    issue_term: pathname        # å¿…å¡«é¡¹ï¼Œä¸issue_numberäºŒé€‰ä¸€å¡«å†™
    issue_number: 100           # å¿…å¡«é¡¹ï¼Œä¸issue_termäºŒé€‰ä¸€å¡«å†™ï¼Œæ¯ç¯‡æ–‡ç« å¯¹åº”ä¸€ä¸ªissueï¼Œå¡«å†™å‰éœ€è¦æ‰‹åŠ¨åˆ›å»ºissue
    label: ğŸ’¬
    theme: github-light
share:
    type: sharethis
    install_url: https://platform-api.sharethis.com/js/sharethis.js#property=63c55b17c2d2a80019406088&product=inline-share-buttons&source=platform
sidebar:
    left:
        sticky: false
    right:
        sticky: false
widgets:
    -
        position: left
        type: profile
        author: InverseDa
        author_title: 
        location: Shenzhen, Guangdong, China
        avatar:
        avatar_rounded: false
        gravatar:
        follow_link: https://github.com/InverseDa
        social_links:
            Github:
                icon: fab fa-github
                url: https://github.com/InverseDa
            Facebook:
                icon: fab fa-facebook
                url: https://facebook.com
            Twitter:
                icon: fab fa-twitter
                url: https://twitter.com
            Dribbble:
                icon: fab fa-dribbble
                url: https://dribbble.com
            RSS:
                icon: fas fa-rss
                url: /
    -
        position: left
        type: toc
        index: true
        collapsed: true
        depth: 3
    -
        position: left
        type: links
        links:
            Hexo: https://hexo.io
            Bulma: https://bulma.io
    -
        position: left
        type: categories
    -
        position: left
        type: recent_posts
    -
        position: left
        type: archives
    -
        position: left
        type: tags
        order_by: name
        amount:
        show_count: true
plugins:
    animejs: true
    back_to_top: true
    baidu_analytics:
        tracking_id:
    bing_webmaster:
        tracking_id:
    busuanzi: false
    cnzz:
        id:
        web_id:
    cookie_consent:
        type: info
        theme: edgeless
        static: false
        position: bottom-left
        policyLink: https://www.cookiesandyou.com/
    gallery: true
    google_analytics:
        tracking_id:
    hotjar:
        site_id:
    katex: false
    mathjax: true
    outdated_browser: false
    progressbar: true
    statcounter:
        project:
        security:
    twitter_conversion_tracking:
        pixel_id:
providers:
    cdn: jsdelivr
    fontcdn: google
    iconcdn: fontawesome
